[package]
name = "tabula"
version = "0.1.0"
edition = "2021"
authors = ["Teia Leusten <teia.leusten@proton.me>"]
description = "A simple command line tool for cryptography and cryptanalysis"

[dependencies]
text_io = "0.1.12"
clap = { version = "4.5.4", features = ["derive"] }
modicum = "0.1.0"
